media:
  input: public/images
  output: /images

content:
  - name: posts
    label: 博客文章
    type: collection
    path: src/data/post
    fields:
      - name: title
        label: 文章标题
        type: string
        required: true
      - name: publishDate
        label: 发布日期
        type: date
      - name: description
        label: 文章摘要
        type: string
      - name: category
        label: 分类
        type: string
      - name: tags
        label: 标签
        type: list
      - name: draft
        label: 存为草稿
        type: boolean
        default: false
      - name: body
        label: 正文内容
        type: rich-text